package br.org.fundatec.view;

import br.org.fundatec.model.Endereco;
import br.org.fundatec.model.Funcionario;
import br.org.fundatec.service.VendaService;

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");

        //Endereco endereco1 = new Endereco ...
        //Endereco endereco2 = new Endereco ...
        //Endereco endereco3 = new Endereco ...
        //Endereco endereco4 = new Endereco ...
        //Endereco endereco5 = new Endereco ...

        //Cliente cliente1 = new Cliente ...
        //Cliente cliente2 = new Cliente ...
        //Cliente cliente3 = new Cliente ...

        //Funcionario funcionario1 = new Funcionario ...
        //Funcionario funcionario2 = new Funcionario ...

        //Imovel imovel1 = new Imovel ...

        //...

        VendaService vendaService = new VendaService();
        //System.out.println("Vendende imovel " + imovel1.getIdImovel());
        //vendaService.venderImovel(funcionario2, cliente3, imovel1);


    }
}